version: '3.7'
services:
  # Template
  #go-service:
  #  build:
  #    dockerfile: dockerfiles/dev.go.dockerfile
  #    context: .
  #  volumes:
  #    - .:/app

  # Environment
  mqtt_broker:
    container_name: mqtt_broker
    image: vimagick/mosquitto
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'device-registry'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql

  # Microservices
  service.connect:
    container_name: connect-service
    links:
      - mqtt_broker
    build:
      dockerfile: services/connect-service/dev.dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 8081:8081

  service.deviceregistry:
    container_name: device-registry
    links:
      - mysql
    build:
      dockerfile: services/device-registry/dev.dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 8081:8081

volumes:
  my-db:
