version: '3.7'
services:
  # Environment
  mqtt_broker:
    container_name: mqtt_broker
    image: vimagick/mosquitto
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'device-registry'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql

  # Microservices
  service.devicebridge:
    links:
      - mqtt_broker
    build:
      dockerfile: ../home-automation-bridge/Dockerfile
      context: .
    ports:
      - 8081:8081
    volumes:
      - .:/app
    restart: always

  # Microservices
  service.deviceregistry:
    links:
      - mysql
    build:
      dockerfile: ../home-automation-device-registry/Dockerfile
      context: .
    ports:
      - 8082:8082
    volumes:
      - .:/app
    restart: always

volumes:
  my-db:
