version: '3.7'
services:
  mosquitto:
    image: vimagick/mosquitto
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883"
    restart: always
  db:
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'device-registry'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql
volumes:
  my-db:
