// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/diogomonte/home-automation/mqtt"
)

// Injectors from wire.go:

func InitializeMqttClient(uri string) common.MqttClient {
	commonMqttClient := common.NewMqttClient(uri)
	return commonMqttClient
}
