// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeMqttClient(uri string) MqttClient {
	mqttClient := NewMqttClient(uri)
	return mqttClient
}
